### ISSUE TITLE
Debug "java.util.concurrent.TimeoutException: Futures timed out after [1 minute]"

### ISSUE THREAD

**Issue by hanswesterbeek** [delving/narthex#110]
Sometimes this stacktrace happens:

```
2016-09-19 17:17:00,578 - [error] akka.dispatch.Dispatcher Slf4jLogger.scala:71 - Futures timed out after [1 minute]
java.util.concurrent.TimeoutException: Futures timed out after [1 minute]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
	at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:167)
	at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640)
```

It's unclear which Future is timing out. Investigate

**Comment by hanswesterbeek** [comment]
Possible offender:

`DsInfo.scala`
```scala
  // could cache as well so that the get happens less
  def futureModel = ts.dataGet(graphName)

  futureModel.onFailure {
    case e: Throwable => Logger.warn(s"No data found for dataset $spec", e)
  }

  def getModel = Await.result(futureModel, patience)
```

**Comment by hanswesterbeek** [comment]
This was caused by a local issue on my machine.
