### ISSUE TITLE
"next on empty iterator"

### ISSUE THREAD

**Issue by hanswesterbeek** [delving/narthex#118]
Stacktrace:
```
java.util.NoSuchElementException: next on empty iterator
    at scala.collection.Iterator$$anon$2.next(Iterator.scala:39)
    at scala.collection.Iterator$$anon$2.next(Iterator.scala:37)
    at scala.collection.MapLike$$anon$2.next(MapLike.scala:216)
    at scala.collection.IterableLike$class.head(IterableLike.scala:107)
    at scala.collection.AbstractIterable.head(Iterable.scala:54)
    at analysis.TreeNode$.apply(TreeNode.scala:88)
    at analysis.Analyzer$$anonfun$receive$1$$anonfun$applyOrElse$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(Analyzer.scala:85)
    at analysis.Analyzer$$anonfun$receive$1$$anonfun$applyOrElse$1$$anonfun$apply$mcV$sp$1.apply(Analyzer.scala:79)
    at analysis.Analyzer$$anonfun$receive$1$$anonfun$applyOrElse$1$$anonfun$apply$mcV$sp$1.apply(Analyzer.scala:79)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:409)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by hanswesterbeek** [comment]
Can be reproduced by hravesting enb-40-beeldmateriaal

**Comment by hanswesterbeek** [comment]
This happens when the file `NarthexFiles/devorg/datasets/enb-40-beeldmateriaal/processed/00000.xml` is empty. Said file is the result of the 'output' step.

**Comment by hanswesterbeek** [comment]
Discuss this with Sjoerd to come up with a correct solution, not just fight symptoms.
