### ISSUE TITLE
Network error on opening thesaurus mapping page when no Thesaurus is uploaded

### ISSUE THREAD

**Issue by kiivihal** [delving/narthex#83]
When you have select a Skos field in the explore stage, save the dataset and then select 'Map vocabulary terms' you will get a network error when no Thesaurus is uploaded. See the stacktrace below for a reproduction in the development environment.

The errormessage  should explain that either a Thesaurus should be created or that content should be uploaded to the Thesaurus on the Thesaurus page.

```
[warn] application - No data found for skos vocabulary http://devorg.localhost/resource/skos/erfgoed-thesaurus/graph
java.lang.RuntimeException: Get response for http://devorg.localhost/resource/skos/erfgoed-thesaurus/graph not 2XX, but 404: No such graph: <http://devorg.localhost/resource/skos/erfgoed-thesaurus/graph>
	at triplestore.Fuseki$$anonfun$dataGet$1.apply(TripleStore.scala:140) ~[classes/:na]
	at triplestore.Fuseki$$anonfun$dataGet$1.apply(TripleStore.scala:138) ~[classes/:na]
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:236) ~[scala-library-2.11.6.jar:na]
	at scala.util.Try$.apply(Try.scala:191) ~[scala-library-2.11.6.jar:na]
	at scala.util.Success.map(Try.scala:236) ~[scala-library-2.11.6.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) ~[scala-library-2.11.6.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) ~[scala-library-2.11.6.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) ~[scala-library-2.11.6.jar:na]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[na:1.8.0_92]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_92]
[error] p.c.s.n.PlayDefaultUpstreamHandler - Cannot invoke the action
java.lang.RuntimeException: Get response for http://devorg.localhost/resource/skos/erfgoed-thesaurus/graph not 2XX, but 404: No such graph: <http://devorg.localhost/resource/skos/erfgoed-thesaurus/graph>
	at triplestore.Fuseki$$anonfun$dataGet$1.apply(TripleStore.scala:140) ~[classes/:na]
	at triplestore.Fuseki$$anonfun$dataGet$1.apply(TripleStore.scala:138) ~[classes/:na]
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:236) ~[scala-library-2.11.6.jar:na]
	at scala.util.Try$.apply(Try.scala:191) ~[scala-library-2.11.6.jar:na]
	at scala.util.Success.map(Try.scala:236) ~[scala-library-2.11.6.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) ~[scala-library-2.11.6.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) ~[scala-library-2.11.6.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) ~[scala-library-2.11.6.jar:na]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[na:1.8.0_92]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_92]
[error] application - 

! @716f871de - Internal server error, for (GET) [/narthex/app/skos/erfgoed-thesaurus/languages] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[RuntimeException: Get response for http://devorg.localhost/resource/skos/erfgoed-thesaurus/graph not 2XX, but 404: No such graph: <http://devorg.localhost/resource/skos/erfgoed-thesaurus/graph>]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[play_2.11-2.4.8.jar:2.4.8]
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[play_2.11-2.4.8.jar:2.4.8]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:277) [play-netty-server_2.11-2.4.8.jar:2.4.8]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:273) [play-netty-server_2.11-2.4.8.jar:2.4.8]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [scala-library-2.11.6.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [scala-library-2.11.6.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.6.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109) [play-iteratees_2.11-2.4.8.jar:2.4.8]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71) [play-iteratees_2.11-2.4.8.jar:2.4.8]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library-2.11.6.jar:na]
Caused by: java.lang.RuntimeException: Get response for http://devorg.localhost/resource/skos/erfgoed-thesaurus/graph not 2XX, but 404: No such graph: <http://devorg.localhost/resource/skos/erfgoed-thesaurus/graph>
	at triplestore.Fuseki$$anonfun$dataGet$1.apply(TripleStore.scala:140) ~[classes/:na]
	at triplestore.Fuseki$$anonfun$dataGet$1.apply(TripleStore.scala:138) ~[classes/:na]
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:236) ~[scala-library-2.11.6.jar:na]
	at scala.util.Try$.apply(Try.scala:191) ~[scala-library-2.11.6.jar:na]
	at scala.util.Success.map(Try.scala:236) ~[scala-library-2.11.6.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) ~[scala-library-2.11.6.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) ~[scala-library-2.11.6.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.6.jar:na]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[na:1.8.0_92]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_92]
[info] application - Loaded http://devorg.localhost/resource/dataset/museum-collectie/skos/graph

```

**Comment by hanswesterbeek** [comment]
@kiivihal *bump* to remind you to provide me with sample dataset and exact steps to take

**Comment by kiivihal** [comment]
This issue can't be reproduced in the current 0.4.1-SNAPSHOT. So for now declaring this issue fixed.
